#!/bin/sh
export PYTHON_AFL_SIGNAL=${PYTHON_AFL_SIGNAL:-SIGUSR1}
if ! command -v afl-showmap > /dev/null
then
    cat >&2 <<EOF
$0: afl-showmap not found
Is AFL <http://lcamtuf.coredump.cx/afl/> installed?
EOF
    exit 127
fi
exec afl-showmap "$@"

# vim:ts=4 sts=4 sw=4 et
