#!/bin/sh
export AFL_SKIP_BIN_CHECK=1
export PYTHON_AFL_SIGNAL=${PYTHON_AFL_SIGNAL:-SIGUSR1}
if ! command -v afl-cmin > /dev/null
then
    cat >&2 <<EOF
$0: afl-cmin not found
Is AFL <http://lcamtuf.coredump.cx/afl/> installed?
EOF
    exit 127
fi
exec afl-cmin "$@"

# vim:ts=4 sts=4 sw=4 et
