#!/bin/sh
export AFL_SKIP_CHECKS=1 # AFL << 1.20b
export AFL_SKIP_BIN_CHECK=1 # AFL >= 1.20b
export AFL_DUMB_FORKSRV=1
prog="${0##*/}"
if [ -n "$PYTHON_AFL_DUMB" ]
then
    # shellcheck disable=SC2016
    printf '%s: $PYTHON_AFL_DUMB is deprecated; use -n instead\n' "$prog" >&2
    set -- -n "$@"
fi
export PYTHON_AFL_SIGNAL="${PYTHON_AFL_SIGNAL:-SIGUSR1}"
export PYTHON_AFL_PERSISTENT=1
if ! command -v afl-fuzz > /dev/null
then
    cat >&2 <<EOF
$prog: afl-fuzz not found
Is AFL <https:://lcamtuf.coredump.cx/afl/> installed?
EOF
    exit 127
fi
exec afl-fuzz "$@"

# vim:ts=4 sts=4 sw=4 et
