#!/bin/sh
export AFL_SKIP_CHECKS=1 # AFL << 1.20b
export AFL_SKIP_BIN_CHECK=1 # AFL >= 1.20b
export AFL_DUMB_FORKSRV=1
if [ -n "$PYTHON_AFL_DUMB" ]
then
    printf '%s: $PYTHON_AFL_DUMB is deprecated; use -n instead\n' "$(basename "$0")" >&2
    set -- -n "$@"
fi
export PYTHON_AFL_SIGNAL=${PYTHON_AFL_SIGNAL:-SIGUSR1}
export PYTHON_AFL_PERSISTENT=1
exec afl-fuzz "$@"

# vim:ts=4 sts=4 sw=4 et
