#!/bin/sh
export AFL_SKIP_BIN_CHECK=1
export PYTHON_AFL_SIGNAL="${PYTHON_AFL_SIGNAL:-SIGUSR1}"
prog="${0##*/}"
if ! command -v afl-cmin > /dev/null
then
    cat >&2 <<EOF
$prog: afl-cmin not found
Is AFL <https://lcamtuf.coredump.cx/afl/> installed?
EOF
    exit 127
fi
exec afl-cmin "$@"

# vim:ts=4 sts=4 sw=4 et
