#!/bin/sh

# Copyright © 2015-2020 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u

usage()
{
    printf 'Usage: %s [--no-build] [pythonX.Y...]\n' "$0"
}

if ! args=$(getopt -n "$0" -o 'hj:' --long 'help,jobs:,no-build' -- "$@")
then
    usage >&2
    exit 1
fi
eval set -- "$args"
opt_jobs=$(nproc) || opt_jobs=1
opt_build=y
while true
do
    case "$1" in
        -h|--help) usage; exit 0;;
        -j|--jobs) opt_jobs=$2; shift 2;;
        --no-build) opt_build=; shift;;
        --) shift; break;;
        *) printf '%s: internal error (%s)\n' "$0" "$1" >&2; exit 1;;
    esac
done

[ $# = 0 ] && set -- python
[ -z $opt_build ] ||
printf '%s\n' "$@" \
| xargs -P"$opt_jobs" -t -I'{python}' env '{python}' setup.py build --build-lib 'build/{python}'
cd ./tests
export PATH="$PWD/..:$PATH"
printf '%s\n' "$@" \
| xargs -t -I'{python}' env PYTHONPATH="$PWD/../build/{python}" '{python}' -c 'import nose; nose.main()' --verbose

# vim:ts=4 sts=4 sw=4 et
