#!/usr/bin/env bash

# Copyright © 2016-2019 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u
set -o pipefail
here=${0%/*}
here=${here#./}
root="$here/../"
root=${root#private/../}
rst2xml=$(command -v rst2xml) \
|| rst2xml=$(command -v rst2xml.py) \
|| { printf 'rst2xml not found\n' >&2; exit 1; }
rst2xml=${rst2xml##*/}
options='--input-encoding=UTF-8 --strict'
if [ $# -eq 0 ]
then
    print_desc='python setup.py --long-description'
    echo "(cd ${root:-.} && $print_desc) | $rst2xml $options - /dev/null" >&2
    (cd "${root:-.}" && $print_desc) | "$rst2xml" $options - /dev/null
fi
if [ $# -eq 0 ]
then
    grep -rwl 'ft=rst' "${root}doc"
else
    printf '%s\n' "$@"
fi |
xargs -L1 -t -I{} "$rst2xml" $options {} /dev/null

# vim:ts=4 sts=4 sw=4 et
