#!/bin/sh

# Copyright © 2015-2022 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u
PYTHON=${PYTHON:-python}
"$PYTHON" -m pylint --version >/dev/null || exit 1
if [ $# -eq 0 ]
then
    set -- setup.py tests/*.py
fi
if [ -n "${VIRTUAL_ENV:-}" ]
then
    # https://github.com/PyCQA/pylint/issues/73
    set -- --ignored-modules=distutils "$@"
fi
log=$(mktemp -t pylint.XXXXXX)
"$PYTHON" -m pylint "$@" > "$log" || [ $? != 1 ]
! grep -P '^\S+:' "$log" \
| grep -v -P ": redefined-builtin \\[.*\\] Redefining built-in '(file|dir|input)'$" \
| grep -v -P ": superfluous-parens \\[.*\\] Unnecessary parens after u?'print' keyword$" \
| LC_ALL=C sort -k2 \
| grep '.' || exit 1
rm "$log"

# vim:ts=4 sts=4 sw=4 et
